### ISSUE TITLE
There is no test-accumulator

### ISSUE THREAD

**Issue by femsub** [seldridge/rocket-rocc-examples#13]
I did everything the Readme said,when i did the last step"**time $ROCKETCHIP_DIR/emulator-freechips.rocketchip.system-RoccExampleConfig -c pk ./build/test-accumulator**",there is no file"test-accumulator"at all.

so after run the command,it show:
```
~/桌面/project/rocket-rocc-examples$ time emulator-freechips.rocketchip.system-RoccExampleConfig -c $RISCV/riscv64-unknown-elf/bin/pk ./build/test-accumulator

This emulator compiled with JTAG Remote Bitbang client. To enable, use +jtag_rbb_enable=1.
Listening on port 33726
couldn't open ELF program: ./build/!
*** FAILED *** via dtm (code = -1, seed 1522044587) after 1469412 cycles

real	3m14.550s
user	3m13.520s
sys	0m0.484s
```

I did the pk test "emulator-freechips.rocketchip.system-RoccExampleConfig pk pk/examples-pk-accumulator",it works well:
```
This emulator compiled with JTAG Remote Bitbang client. To enable, use +jtag_rbb_enable=1.
Listening on port 35611
[INFO] Write R[1] = 0xdead
[INFO] Read R[1]
[INFO]   Received 0xdead (expected 0xdead)
[INFO] Accum R[1] with 0xffffffffffffe042
[INFO] Read R[1]
[INFO]   Received 0xbeef (expected 0xbeef)
[INFO] Load 0xbad (virt: 0x0xfee9b00, phys: 0x0x8ffffb00) via L1 virtual address
[INFO] Read R[1]
[INFO]   Received 0xbad (expected 0xbad)
```

I think i'm just not find the file "test-accumulator" in floder“build”

**Comment by seldridge** [comment]
Whoops... I forgot to update the README after refactoring how the tests were organized. Thanks for reporting this.

This should now be fixed with an updated README where `test-accumulator` is now changed to `examples-pk-accumulator`. Let me know if you see any other inconsistencies here.
