### ISSUE TITLE
An illegal instruction was executed!

### ISSUE THREAD

**Issue by chenxuhao** [seldridge/rocket-rocc-examples#15]
I did apply the patch and rebuild pk (configure, make and make install).

I have a problem when running the Proxy Kernel test with the emulator:

$ ./emulator-freechips.rocketchip.system-RoccExampleConfig pk ../rocket-rocc-examples/build/pk/examples-pk-accumulator
This emulator compiled with JTAG Remote Bitbang client. To enable, use +jtag_rbb_enable=1.
Listening on port 44165
[INFO] Write R[1] = 0xdead
z 0000000000000000 ra 00000000000101e8 sp 000000000fee9ad0 gp 000000000001d6a8
tp 0000000000000000 t0 0000000000010560 t1 0000000000040000 t2 0000000000000000
s0 000000000fee9b20 s1 0000000000000000 a0 000000000000001b a1 000000000000dead
a2 0000000000000001 a3 0000000000000000 a4 0000000000000000 a5 0000000000000001
a6 000000000000001f a7 0000000000000040 s2 0000000000000000 s3 0000000000000000
s4 0000000000000000 s5 0000000000000000 s6 0000000000000000 s7 0000000000000000
s8 0000000000000000 s9 0000000000000000 sA 0000000000000000 sB 0000000000000000
t3 000000000000000a t4 0000000000000000 t5 0000000000000000 t6 0000000000000000
pc 00000000000101f4 va 0000000000c5f50b insn 00c5f50b sr 8000000200046020
An illegal instruction was executed!
*** FAILED *** via dtm (code = -1, seed 1531194881) after 3611144 cycles

However, the baremetal test works fine:

./emulator-freechips.rocketchip.system-RoccExampleConfig ../rocket-rocc-examples/build/bareMetal/examples-bareMetal-p-accumulator
This emulator compiled with JTAG Remote Bitbang client. To enable, use +jtag_rbb_enable=1.
Listening on port 45235

Using spike, I got this:

$ spike ../rocket-rocc-examples/build/bareMetal/examples-bareMetal-p-accumulator
*** FAILED *** (tohost = 668)

$ spike pk ../rocket-rocc-examples/build/pk/examples-pk-accumulator
[INFO] Write R[1] = 0xdead
z 0000000000000000 ra 00000000000101e8 sp 000000007f7e9ad0 gp 000000000001d6a8
tp 0000000000000000 t0 0000000000010560 t1 0000000000040000 t2 0000000000000000
s0 000000007f7e9b20 s1 0000000000000000 a0 000000000000001b a1 000000000000dead
a2 0000000000000001 a3 0000000000000000 a4 0000000000000000 a5 0000000000000001
a6 000000000000001f a7 0000000000000040 s2 0000000000000000 s3 0000000000000000
s4 0000000000000000 s5 0000000000000000 s6 0000000000000000 s7 0000000000000000
s8 0000000000000000 s9 0000000000000000 sA 0000000000000000 sB 0000000000000000
t3 000000000000000a t4 0000000000000000 t5 0000000000000000 t6 0000000000000000
pc 00000000000101f4 va 0000000000c5f50b insn 00c5f50b sr 8000000200046020
An illegal instruction was executed!

Any ideas?

Best regards,
Xuhao

**Comment by seldridge** [comment]
Haven't had a chance to test this on my end. Were you able to sort it out?

**Comment by chenxuhao** [comment]
yes, I've resolved it. It was related to the install path of pk. Thanks!
