### ISSUE TITLE
Complie custom instructions error

### ISSUE THREAD

**Issue by hongber** [seldridge/rocket-rocc-examples#16]
I want to use custom instructions,macro to pass rs1_ and rs2_ as immediates. When I complie them,it generate errors.

**Comment by seldridge** [comment]
Yeah, the macros don't currently support this. This is just something that I never got around to adding back in. A PR would be welcome, though!

Take a look at: https://github.com/IBM/rocc-software/blob/master/src/xcustom.h#L80. I think you can replicate how this works for the `*_R_R_R` variant to support a `*_R_I_I` variant.

I'm closing this is an IBM/rocc-software issue. Feel free to re-open if I'm mistaken.
