### ISSUE TITLE
Building configuration failed

### ISSUE THREAD

**Issue by sanket2608** [seldridge/rocket-rocc-examples#18]
Hi, I've built toolchain for march rv32imac and  mabi ilp32. My emulator is also 32 bit. Is there anyway to build configuration for 32 bit. I'm getting following error...

**make[1]: riscv64-unknown-elf-gcc: Command not found**
/home/sanket/rocc-eg/rocket-rocc-examples/build/../bareMetal/Makefile:24: recipe for target 'examples-bareMetal-p-accumulator' failed
make[1]: *** [examples-bareMetal-p-accumulator] Error 127

Please assist..
Thanks  & Regards,

**Comment by seldridge** [comment]
You should be able to change the `XLEN` with `make XLEN=32`. (Which is really just overriding the variable here: https://github.com/seldridge/rocket-rocc-examples/blob/master/Makefrag#L1)

**Comment by sanket2608** [comment]
> You should be able to change the `XLEN` with `make XLEN=32`. (Which is really just overriding the variable here: https://github.com/seldridge/rocket-rocc-examples/blob/master/Makefrag#L1)

Thanks for reply.. 
I've changed XLEN in Makefrag but still XLEN in Makefile is 64. Even i try with changing XLEN in  Makefile which is in build folder but it's not working.
I'm getting same error..

Thanks...

**Comment by seldridge** [comment]
Ah, sorry. Did you try `make XLEN=32`? (I probably should have been more clear that that's what I meant.)

If I run this locally, I see it trying to use `riscv32-unknown-elf-gcc` which is what I think you want:

```
# make XLEN=32
mkdir -p bareMetal
make -C bareMetal -f /home/schuyler/repos/github.com/seldridge/rocket-rocc-examples/build/../bareMetal/Makefile abs_top_srcdir=/home/schuyler/repos/github.com/seldridge/rocket-rocc-examples/build/.. XLEN=32 PREFIX=examples-bareMetal src_dir=/home/schuyler/repos/github.com/seldridge/rocket-rocc-examples/build/../bareMetal RISCVTOOLS=foo
make[1]: Entering directory '/home/schuyler/repos/github.com/seldridge/rocket-rocc-examples/build/bareMetal'
riscv32-unknown-elf-gcc  -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -I/home/schuyler/repos/github.com/seldridge/rocket-rocc-examples/build/.. -Ifoo -DID_STRING= -Ifoo/riscv-tests/env/p -Tfoo/riscv-tests/env/p/link.ld /home/schuyler/repos/github.com/seldridge/rocket-rocc-examples/build/../bareMetal/accumulator.S  -o examples-bareMetal-p-accumulator 
make[1]: riscv32-unknown-elf-gcc: Command not found
```

While I do not have a 32-bit toolchain installed (nor riscv-tools anywhere) and this consequently errors out, I think it should work for you as long as you have your 32-bit newlib toolchain in your path (you should have `riscv32-unknown-elf-gcc` in your PATH).

**Comment by sanket2608** [comment]
Hi Seldridge,
          I was trying to put this code over fpga. I've generated chip for following configuration

_class MyConfig extends Config (new WithoutTLMonitors ++ new TinyConfig++new WithJtagDTMSystem++ new RoccExampleConfig )_

As per chisel code for roccexample .. 
_for doAccum instruction opcode is "0001011". func3 ="111"and
func7="0000011"
and i've taken a0,a1,a2 as rd,rs1 and rs2 respectively.
So i got 0x06c5f50b._
Please correct me if i'm wrong.
but while executing specifically this line of program PC jumped over zero.

Please correct me. I guess, i messed while conversion. xD
Thanks..

**Comment by sanket2608** [comment]
> Hi Seldridge,
> I was trying to put this code over fpga. I've generated chip for following configuration
> 
> _class MyConfig extends Config (new WithoutTLMonitors ++ new TinyConfig++new WithJtagDTMSystem++ new RoccExampleConfig )_
> 
> As per chisel code for roccexample ..
> _for doAccum instruction opcode is "0001011". func3 ="111"and func7="0000011" and i've taken a0,a1,a2 as rd,rs1 and rs2 respectively. So i got 0x06c5f50b._
> Please correct me if i'm wrong.
> but while executing specifically this line of program PC jumped over zero.
> 
> Please correct me. I guess, i messed while conversion. xD
> Thanks..

i've put my own small assembly program which is just intialising a0,a1 and a2 and calling doAccum instruction

**Comment by sanket2608** [comment]
> Ah, sorry. Did you try `make XLEN=32`? (I probably should have been more clear that that's what I meant.)
> 
> If I run this locally, I see it trying to use `riscv32-unknown-elf-gcc` which is what I think you want:
> 
> ```
> # make XLEN=32
> mkdir -p bareMetal
> make -C bareMetal -f /home/schuyler/repos/github.com/seldridge/rocket-rocc-examples/build/../bareMetal/Makefile abs_top_srcdir=/home/schuyler/repos/github.com/seldridge/rocket-rocc-examples/build/.. XLEN=32 PREFIX=examples-bareMetal src_dir=/home/schuyler/repos/github.com/seldridge/rocket-rocc-examples/build/../bareMetal RISCVTOOLS=foo
> make[1]: Entering directory '/home/schuyler/repos/github.com/seldridge/rocket-rocc-examples/build/bareMetal'
> riscv32-unknown-elf-gcc  -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -I/home/schuyler/repos/github.com/seldridge/rocket-rocc-examples/build/.. -Ifoo -DID_STRING= -Ifoo/riscv-tests/env/p -Tfoo/riscv-tests/env/p/link.ld /home/schuyler/repos/github.com/seldridge/rocket-rocc-examples/build/../bareMetal/accumulator.S  -o examples-bareMetal-p-accumulator 
> make[1]: riscv32-unknown-elf-gcc: Command not found
> ```
> 
> While I do not have a 32-bit toolchain installed (nor riscv-tools anywhere) and this consequently errors out, I think it should work for you as long as you have your 32-bit newlib toolchain in your path (you should have `riscv32-unknown-elf-gcc` in your PATH).

rocc-eg/rocket-rocc-examples/build$ sudo make XLEN=32
mkdir -p bareMetal
make -C bareMetal -f /home/sanket/rocc-eg/rocket-rocc-examples/build/../bareMetal/Makefile abs_top_srcdir=/home/sanket/rocc-eg/rocket-rocc-examples/build/.. XLEN=32 PREFIX=examples-bareMetal src_dir=/home/sanket/rocc-eg/rocket-rocc-examples/build/../bareMetal **RISCVTOOLS=/opt/riscv**
make[1]: Entering directory '/home/sanket/rocc-eg/rocket-rocc-examples/build/bareMetal'
riscv32-unknown-elf-gcc  -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -I/home/sanket/rocc-eg/rocket-rocc-examples/build/.. -I/opt/riscv -DID_STRING= -I/opt/riscv/riscv-tests/env/p -T/opt/riscv/riscv-tests/env/p/link.ld /home/sanket/rocc-eg/rocket-rocc-examples/build/../bareMetal/accumulator.S  -o examples-bareMetal-p-accumulator 
make[1]: riscv32-unknown-elf-gcc: Command not found
/home/sanket/rocc-eg/rocket-rocc-examples/build/../bareMetal/Makefile:24: recipe for target 'examples-bareMetal-p-accumulator' failed
make[1]: *** [examples-bareMetal-p-accumulator] Error 127
make[1]: Leaving directory '/home/sanket/rocc-eg/rocket-rocc-examples/build/bareMetal'
Makefile:18: recipe for target 'bareMetal' failed
make: *** [bareMetal] Error 2
**sanket@sanketk3:~/rocc-eg/rocket-rocc-examples/build$ riscv32-unknown-elf-gcc
riscv32-unknown-elf-gcc: fatal error: no input files**
compilation terminated.

xD still getting error.. I don't know why but i tried with make XLEN=32..
riscv32-unknown-elf-gcc is in path.. even **RISCVTOOLS** path is also correct

Thanks for reply

**Comment by sanket2608** [comment]
Thanks for help it worked with make XLEN=32
but now i'm getting other issue..

 **fatal error: riscv_test.h: No such file or directory
    1 | #include "riscv_test.h"
      |          ^~~~~~~~~~~~~~**

**Comment by sanket2608** [comment]
Thanks for help.....
There are issues with printf functions it is throwing many errors for usage of **long unsigned int**

I tried with riscv64 bit toolchain it is working fine..

**Comment by seldridge** [comment]
Try it without `sudo` to build. There shouldn't be a need to do that and root will have a different path than your user.

Yeah, there's a bunch of `%lx` in the proxy kernel printfs as well as `uint64_t`. I think you could safely change those to `%x` and `uint32_t`, but there should be a way to convert this to work for 32 bit or 64 bit XLEN.

I had never considered using this for 32-bit builds...
