### ISSUE TITLE
csrrs instruction illegal with proxy kernel?

### ISSUE THREAD

**Issue by hawkcl** [seldridge/rocket-rocc-examples#21]
Hi,
I have a simple test for RoCC interrupt. The baremetal test works as expected. When I run it with proxy kernel, it error out with illegal instruction. I found out the illegal instruction is the csrrs instruction. 
I am running with the patched proxy kernel. 
Any idea to fix this? Thanks.

Lei

**Comment by seldridge** [comment]
Is it the csrrs instruction in the patch that is used to set the XS bits?

I have not run the proxy kernel using that patch in some time. However, there's circumstantial evidence that that approach, or something like it, should still work [given that Gemmini is working with the proxy kernel](https://github.com/IBM/rocc-software/pull/5#issuecomment-588428994).

**Comment by hawkcl** [comment]
It is the csrrs instruction in my testing code. I need to handle the RoCC interrupt in my testing code. I think Gemmini interrupt is used for address translation, and it is handled by the core.

**Comment by seldridge** [comment]
The user-level spec states:

> Attempts to access a non-existent CSR raise an illegal instruction exception. Attempts to access a
CSR without appropriate privilege level or to write a read-only register also raise illegal instruction
exceptions.

I would interpret that as your `csrrs` instruction is running without sufficient privilege to do what you are trying to do. I think that if you run a test under the proxy kernel, that's user mode, while running bare metal is likely machine mode (this may be wrong).

**Comment by hawkcl** [comment]
Very likely. Thanks a lot.
