### ISSUE TITLE
Testing accumulator.c using a Linux kernel instead of pk

### ISSUE THREAD

**Issue by pierceja** [seldridge/rocket-rocc-examples#5]
Hello,
First I would like to say thank you for this repo. I'm new to rocket chip, but this repo has helped me a lot with setting up custom RoCC extensions and testing them. My goal in the future is to eventually be able to run C files on the chip using libraries not supported by pk. What would the steps be to run the accumulator.c test file (to test my RoCC extension) on the rocket chip emulator without using pk, but using a Linux kernel and compiler instead? Is this possible using the emulator or would I have to use spike?
Thanks!

**Comment by seldridge** [comment]
I'm glad to know that you've found it beneficial!

> What would the steps be to run the accumulator.c test file (to test my RoCC extension) on the rocket chip emulator without using pk, but using a Linux kernel and compiler instead?

Two part answer. First is just related to building Linux as I do not believe that HTIF supports block devices (i.e., disks).

1. Build the userland environment (usually busybox)
2. Build the Linux kernel for RISC-V using an initial ramdisk that includes the userland and likely any other programs you want to run
3. Build bbl (part of the riscv-pk repo) giving it the `--with-payload` option to point at the uncompressed built kernel (vmlinux)

Then run this on your platform (e.g., `spike bbl`). Chris Celio has a bare bones repo that will do this for you: https://github.com/ccelio/initramfs_linux_flow. That may be a good reference point.

Second, you will need to modify the kernel to support RoCCs. Roughly this is the same as the modification for `pk` except that `pk` is intended to ever only really run one program. With Linux, context switching can happen. So... if you do this correctly, then you will save and restore RoCC state whenever you do a context switch. Modifications would be to extend the `task_struct` in Linux to have fields for the RoCC state. You would then do something like how the MSTATUS_FS bits work and set them appropriately based on whether or not a program can use the FPU. Same deal for MSTATUS_XS (which is what is gating if RoCC instructions are going to trigger illegal instruction).

The kludgy way if you don't need something correct and secure is to just enable MSTATUS_XS globally. I haven't looked at this in a long time, so I can't remember where to do that. Note: just enabling this globally will allow two processes to stomp on each other's RoCC state. Likely fine for some quick tests.

> Is this possible using the emulator or would I have to use spike?

Possible, yes. Very, very slow. Emulator is ~10KHz. You're into multiple hours to get through the boot sequence on this (in addition to loading the ~5MB bbl + Linux + ramdisk through the debug interface). So, you're into the realm of either `spike` or running this on an FPGA (25MHz).

**Comment by pierceja** [comment]
Sorry for the late reply. I will give this a shot.

I did have one more question, but it is on a separate topic (I can create a new issue if you would like me to).  I was looking through the LazyRoCC.scala file and was able to see how some of the custom defined instructions are translated into hardware functionality. I was, however, unable to find where the doRead instruction is defined. If I understand the accumulator tests correctly, it looks like doWrite will write a value into a register and doRead will read the value from one register into another? I was just wondering where I could find where doRead was defined in the scala files.

Thanks!

**Comment by seldridge** [comment]
(Apologies, I've been away.)

It looks like `doRead` is implicitly going to perform a read, as opposed to explicitly use the function code of what you pass over the RoCC interface. A response is generated if the `xd` bit is set (which means, "this instruction generates a register response"). This will then return the contents of whatever you specify via an address in `rs1`. 

However, as you do intuit, `doRead` is defined, but not used in any explicit way.

**Comment by seldridge** [comment]
Closing this as I think this answers the question. Reopen if that's not the case.
