### ISSUE TITLE
xcustom.h compile error

### ISSUE THREAD

**Issue by kenzhang82** [seldridge/rocket-rocc-examples#8]
First I would like to thank you for your great example to interact with ROCC, it has been really helpful!!!

So I have been using your accumulator example, but when I compile the code, I got an error saying there is "lvalue required as left operand of assignment" in line (https://github.com/IBM/rocc-software/blob/022e8a51d6ea91e1dfa82c78478904a3d9986b9c/src/xcustom.h#L56). 

When I modified it using "==" everything works fine, but I didn't get a return value from accelerator, could you tell me what would be my source of error here?

Thank you very much!

Regards,
Dong

**Comment by seldridge** [comment]
HI Dong,

Hmm... this is odd. Can you provide a full trace of the error (starting from `../configure --with-riscvtools`, through `make`)  as well as some information about what version of the toolchain you're using? And, this is just compiling things unmodified or are you trying to use some of the macros?

My first guess would be that this is a versioning issue of the toolchain. I'm on riscv-tools `9868299` from 2017-12-26 (which is the submodule of rocket-chip master).

The fix that you're positing won't work, as it's equivalent to changing:
```c
int x, y;
x = y;
```
to:
```c
int x, y;
x == y;
```
Which would just result in nothing happening.

**Comment by kenzhang82** [comment]
Thanks!

I am using the pre-compiled toolchain downloaded from SiFive website (https://www.sifive.com/products/tools/) but an older version (it is compiled on August). 

I manually modified the macro to:

register uint64_t rd_  asm ("x" # rd_n); = (uint64_t) rd;

Do you think that would work?

**Comment by seldridge** [comment]
Nah, that fix still won't do it. 

Okay, an August toolchain sounds like the issue.

I tried quickly with the recent SiFive toolchain. That should build fine for you. Can you test that out and see if it works for you?

**Comment by kenzhang82** [comment]
Thank you for your quick reply and sorry for the stupid question..

I will try that out now and get back to you!

**Comment by kenzhang82** [comment]
I tried the latest toolchain, and I still got the same compile error:

The following is the error I got:

xcustom.h:56:8: error: lvalue required as left operand of assignment
     rd = rd_;                                                           \
        ^
xcustom.h:43:3: note: in expansion of macro 'ROCC_INSTRUCTION_R_R_R'
   ROCC_INSTRUCTION_R_R_R(x, rd, rs1, rs2, funct, 10, 11, 12)
   ^~~~~~~~~~~~~~~~~~~~~~
acc_instr_test.c:35:5: note: in expansion of macro 'ROCC_INSTRUCTION'
     ROCC_INSTRUCTION(XCUSTOM_ACC, x_0, data[0], addr, k_DO_PUSH);
     ^~~~~~~~~~~~~~~~

Any idea?

I am trying to swap the order (i.e. rd_ = rd), but haven't tried if it works.

**Comment by seldridge** [comment]
I'll need some more information... Specifically, a full output of what you're seeing, starting from `../configure` and including you running `make`. I'm assuming that you're just trying to build this repository and that's where the error is coming up?

**Comment by kenzhang82** [comment]
Sure.

I am trying to integrate an accelerator example into Freedom E300 platform (sifive), and I am using freedom-e-sdk for the software, so I have created an example software, and copy xcustom.h and accumulator.h and your accumulator.c over to freedom-e-sdk. That was how I compile the software using sifive flow.

But I got the compilation error as shown above, and I am expecting to see it all compiled and the result from accelerator being put to rd is non-zero. But I cannot get the program compiled.

**Comment by seldridge** [comment]
From looking at what you have, I think you're passing in something weird for `x_0` which is an invalid lvalue. I'd try looking at that. The full text of `acc_instr_test.c` would help and additionally how you're compiling it.

**Comment by kenzhang82** [comment]
Sorry for the late reply. I finally figured out what was wrong. Correct me if I am wrong.

I tried to put ROCC_INSTRUCTION (XCUSTOM_ACC, x_0, data[0], addr, k_DO_WRITE) into the program where x_0 is being defined as constant 0.

When I looked at the macro in xcustom.h, the second argument of ROCC_INSTRUCTION is defined as a register, so I put an undefined variable in there instead, and the program compiles.

But for write, we are not expecting anything from rd (destination register), right? Even this, we still have to pass rd to write instruction?

Sorry for the confusion.

Thanks,
Dong

**Comment by seldridge** [comment]
Yes, this is the issue.

You have to pass a real thing that you can write to (an lvalue) into that macro. This is more a limitation of macro processing (or my ability to write increasingly complex macros) than anything. 

One way around this is with another macro. [Try the new `ROCC_INSTRUCTION_0_R_R`](https://github.com/IBM/rocc-software/blob/master/src/xcustom.h#L71).

**Comment by kenzhang82** [comment]
Thanks for the quick reply @seldridge!

Great, I will try that out and get back to you.

**Comment by kenzhang82** [comment]
I just tried out your macro, this works very well! Thank you very much.

I guess I could go ahead and close the issue now. :)
