### ISSUE TITLE
Connecting RoCC to system

### ISSUE THREAD

**Issue by kenzhang82** [seldridge/rocket-rocc-examples#9]
Hi @seldridge,

This might be off topic (let me know if this is, I will close this issue then), but I am stuck in connecting RoCC to system level. I've got one accelerator (accumulator example) instantiated as per instruction available here: (https://github.com/freechipsproject/rocket-chip/blob/7e75d63ba6b4c1b50aaaf920e1c693ef6acf51d7/src/main/scala/tile/LazyRoCC.scala).

If I understand it correctly, this instantiates the accelerator inside rocket tile, which is wrapped by rocket coreplex, which in turn wrapped by system.

I am just wondering if there is any way to connect the RoCC interface to system level? I am assuming we need some kind of traits like this (https://github.com/freechipsproject/rocket-chip/blob/7e75d63ba6b4c1b50aaaf920e1c693ef6acf51d7/src/main/scala/system/ExampleRocketSystem.scala#L13)? Thanks!

Best,
Dong

**Comment by seldridge** [comment]
Roughly, that's the right approach. Define traits that will expose the signals that you want and then define a coreplex and system that mix those in.

There are kludgy alternatives to do what you want, specifically, using Firrtl's Wiring Transform to pull signals all the way to the top.

**Comment by kenzhang82** [comment]
I might take the second approach you suggested and clean up the code base by various traits later (or whichever is easier). Could you let me know specifically what I need to look for (or if you could give me an example of how to connect one pin of RoCC out to the top that would be perfect!)? Sorry for asking stupid questions.

Thanks,
Dong

**Comment by seldridge** [comment]
The Wiring Transform approach is a bit kludgy currently, but it may work. I'd suggest that this is a more advanced approach than modifying the Chisel, however, as it's diving into concepts which you usually don't have to deal with from working with Rocket Chip.

I'll close this in favor of the Rocket Chip issue: https://github.com/freechipsproject/rocket-chip/issues/1233.
